intel/device-modeling-language

.github/workflows/blocking-issues.yml
Details:
https://github.com/Levi-Lesches/blocking-issues
Senses when you type "Blocked by: #N" in an issue or PR.
=> Enable "Blocking Issues" github action

Makefile, md_to_github.py, validate_md_links.py
- Refactor script to avoid side-effects on toplevel
- Generate github wiki
=> Generate github wiki

MODULEINFO, Makefile, doc/1.4/language.md, py/dml/structure.py, py/dml/template.py, py/dml/topsort.py, py/dml/topsort_test.py, py/dml/traits.py, test/1.4/statements/T_log.dml
- Improve logging test
- Mention that sizeoftype does not count as a constant
- Move topsort to module traits
- Refactor: Move method sorting to traits.py
=> Lost and found patches

RELEASENOTES-1.4.docu, lib/1.4/dml-builtins.dml
Previously https://github.com/intel/device-modeling-language/pull/8
=> Dml regview fix 2

py/dml/c_backend.py, py/dml/dmlc.py, test/depfile.py, test/tests.py
Prerequisite for https://github.com/intel-innersource/applications.simulators.simics.simics-base/pull/1110
=> Implement dependencies for Ninja build

MODULEINFO, Makefile, generate_env.py, py/dml/ctree_test.py, py/dml/dmlc.py, py/dml/dmlparse.py, py/dml/types.py, test/tests.py
- Remove run-time dependency on simicsutils
- Check explicitly for utf8_mode
=> Add support for pypy as interpreter

doc/1.4/language.md, py/dml/dmlparse.py, py/dml/toplevel.py, test/1.4/errors/T_ECONDINEACH.dml
=> Update docs re. `in each` in #if; true/false in experimental #if -- SIMICS-18702

lib/1.4/dml-builtins.dml, test/1.4/lib/T_field.dml, test/1.4/lib/T_field.py
=> Repair documentation of field access order, and add test

RELEASENOTES-1.4.docu, doc/1.4/language.md, include/simics/dmllib.h, py/dml/c_backend.py, py/dml/codegen.py, py/dml/crep.py, py/dml/ctree.py, py/dml/dmllex14.py, py/dml/dmlparse.py, py/dml/messages.py, py/dml/objects.py, py/dml/structure.py, py/dml/traits.py, py/dml/traits_test.py, test/1.4/errors/T_EINDEPENDENTVIOL.dml, test/1.4/errors/T_ESYNTAX_method_qualifiers.dml, test/1.4/errors/T_ETYPEDPARAMVIOL.dml, test/1.4/methods/T_independent.dml, test/1.4/methods/T_startup.dml, test/1.4/methods/T_startup.py, test/1.4/methods/T_startup_memoized.dml, test/1.4/methods/T_startup_memoized.py, test/1.4/statements/T_export.dml, test/tests.py
=> Independent methods -- SIMICS-6181, SIMICS-6182, SIMICS-17632

RELEASENOTES-1.4.docu, py/dml/ctree.py, py/dml/expr.py, py/dml/structure.py, test/1.2/misc/devinfo.dml, test/1.4/errors/T_EBITRN.dml, test/1.4/errors/T_EBITRO.dml, test/1.4/errors/T_EBITRR.dml, test/1.4/errors/T_EBTYPE.dml, test/1.4/errors/T_EUNDEF.dml, test/1.4/lib/T_indices.dml, test/1.4/misc/devinfo.dml, test/tests.py
Design questions still pending, such as whether overlapping ranges should be an error or a warning.
=> Add field range checks in 1.4 -- SIMICS-19194

py/README.md
The readme itself is in need of an update, but that'll require a bigger, slower PR.
=> Remove self-defeatist coment in DMLC hacking guide

RELEASENOTES-1.2.docu, py/dml/structure.py, test/1.2/misc/T_import_dml14.dml, test/1.2/misc/dml14.dml
_this bug_
hjälpe gud min arma själ
=> Fix issue where certain 1.4 params couldn't referenced in 1.2 modules

py/dml/ctree.py, test/1.2/operators/T_cast.dml, test/1.4/errors/T_ECAST.dml
This needs to be tested against VP.
=> Whitelist based type checking for casts -- SIMICS-17955

py/dml/c_backend.py, py/dml/codegen.py, py/dml/ctree.py, py/dml/ctree_test.py, py/dml/dmlc.py, py/dml/dmlparse.py, py/dml/expr.py, py/dml/int_register.py, py/dml/io_memory.py, py/dml/logging.py, py/dml/messages.py, py/dml/output.py, py/dml/serialize.py, py/dml/structure.py, py/dml/symtab.py, py/dml/toplevel.py, py/dml/traits.py, test/tests.py
- Revert previous SimpleSite change
- Polish site strings
- Don't generate #line directives for SimpleSite
=> Don't generate #line directives for SimpleSite

lib/1.4/dml-builtins.dml
=> Clarify documentation for the `destroy` method

RELEASENOTES-1.4.docu, doc/1.4/language.md, include/simics/dmllib.h, py/dml/c_backend.py, py/dml/ctree.py, py/dml/serialize.py, test/1.4/expressions/T_identity.dml, test/1.4/serialize/T_saved_declaration.dml, test/1.4/serialize/T_saved_declaration.py
Depends on #125. Also makes casts of constant object references to template types constant expressions.
=> Serializable template types -- SIMICS-18507

py/dml/dmlparse.py, test/1.4/errors/T_ESYNTAX_zero.dml
=> Only report None tokens as EOF

test/bugs/T_24144.dml, test/bugs/T_6227.dml
=> Remove questionable code

doc/1.4/language.md, lib/1.4/dml-builtins.dml, py/dml/messages.py, validate_md_links.py
- Check that we don't write -- in markdown
=> Check that we don't write -- in markdown

test/tests.py
Binaries moved back from bin/py3 to bin.
Should be merged together with https://github.com/intel-innersource/applications.simulators.simics.simics-base/pull/2205
=> Update binaries path

RELEASENOTES-1.4.docu, include/simics/dmllib.h, lib/1.2/dml-builtins.dml, lib/1.4/dml-builtins.dml, py/dml/c_backend.py, py/dml/ctree.py, py/dml/ctree_test.py, py/dml/expr.py, py/dml/expr_util.py, py/dml/objects.py, py/dml/structure.py, test/1.2/internal/saved_object.dml, test/1.2/structure/T_attribute_conf.dml, test/1.2/structure/T_attribute_conf.py, test/1.4/errors/T_EABSTEMPLATE.dml, test/1.4/structure/T_connect_array.dml, test/1.4/structure/T_connect_array.py, test/1.4/structure/T_subobjs.dml, test/1.4/structure/T_subobjs.py
Currently only works for top-level, non-array attribute objects.
=> Softcode attribute registration

RELEASENOTES-1.4.docu, py/dml/c_backend.py, py/dml/codegen.py, py/dml/globals.py, py/dml/objects.py, py/dml/serialize.py, py/dml/structure.py, test/1.4/serialize/T_saved_dead_vtable.dml, test/1.4/structure/T_trait_dce.dml
I'm not overly happy with the implementation.
=> Make vtables live when the template type is serialized -- SIMICS-20301

RELEASENOTES-1.4.docu, py/dml/types.py, test/tests.py
windows.h defines a macro 'interface'.
Reported by Li Wang and Liang Yi
=> Dodge name clash

test/1.2/events/T_after_chk_dup.py, test/1.2/events/T_dup.py, test/1.4/events/T_after_chk.py
This is required by https://github.com/intel-innersource/applications.simulators.simics.simics-base/pull/2805
=> Run tests in mini-python

RELEASENOTES-1.4.docu
=> Add releasenote for --coverity option

RELEASENOTES-1.4.docu, doc/1.4/language.md, py/dml/codegen.py, py/dml/ctree.py, py/dml/dmlparse.py, py/dml/expr.py, py/dml/messages.py, test/1.4/errors/T_ESYNTAX_arg_inits.dml, test/1.4/syntax/T_argument_initializers.dml
I wanted to implement this before starting implementation of RAII proper.
=> Initializer syntax for arguments -- SIMICS-20473

test/1.4/hooks/T_checkpointing.py
=> Avoid deprecated option forms

test/tests.py
simics_base_path() is more well-defined
=> Avoid internal function simics_root_path

MODULEINFO, test/tests.py
This depends on https://github.com/intel-innersource/applications.simulators.simics.simics-base/pull/4282
=> Add 7-specific dmlc groups

include/simics/dmllib.h
See [this](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=12154207). Hoping this will fix it, will make a Test W run before merging.
=> Soothe static analysis on Windows

test/1.2/structure/T_attribute_conf.py
CORE_write_configuration_persistent to
SIM_write_configuration_state
=> Change of API Simics-21363

RELEASENOTES.docu, lib/1.2/dml-builtins.dml, lib/1.4/dml-builtins.dml, py/dml/compat.py, py/dml/dmlc.py, py/dml/messages.py, test/1.4/legacy/T_port_proxy_attrs_disabled.dml, test/1.4/legacy/T_port_proxy_ifaces_disabled.dml, test/1.4/legacy/T_suppress_WLOGMIXUP_disabled.dml, test/1.4/legacy/T_suppress_WLOGMIXUP_enabled.dml, test/tests.py
@MagnusIntel Adding you as reviewer as I'm interested whether you think the documentation for `suppress_WLOGMIXUP` is sufficient or needs something more.
=> Make the suppression of `WLOGMIXUP` a proper compatibility feature

test/tests.py
This is in preparation for moving Python to an addon package.
=> Use project mini-python

RELEASENOTES-1.4.docu, doc/1.4/language.md, py/dml/ctree_test.py, py/dml/types.py, test/1.2/operators/T_sizeof.dml, test/1.4/serialize/T_saved_declaration.dml, test/1.4/serialize/T_saved_declaration.py
- Repair test
- Add uint64_t and int64_t types
=> Add uint64_t and int64_t types

RELEASENOTES.docu, lib/1.2/dml-builtins.dml, lib/1.4/dml-builtins.dml, py/dml/c_backend.py, py/dml/clone_test.py, py/dml/codegen.py, py/dml/compat.py, py/dml/ctree.py, py/dml/ctree_test.py, py/dml/messages.py, py/dml/types.py, test/1.2/errors/T_EBTYPE.dml, test/1.2/errors/T_ETREC.dml, test/1.4/errors/T_ECONSTFUN.dml, test/1.4/errors/T_EFUNARRAY.dml, test/1.4/errors/T_EFUNSTRUCT.dml, test/1.4/errors/T_EIMPLMEMBER.dml, test/1.4/errors/T_EMETH.dml, test/1.4/errors/T_ESERIALIZE.dml, test/1.4/legacy/T_function_in_extern_struct_disabled.dml, test/1.4/legacy/T_function_in_extern_struct_enabled.dml, test/1.4/legacy/function_in_extern_struct.dml
- **Factor out methods**
- **Test and repair `const` variants of all types**
=> Test and repair `const` variants of all types

py/dml/types.py, test/1.4/misc/linemarks.dml, test/tests.py
- **Polish messages for test failures**
- **Improve linemarks for struct declarations**
=> Improve linemarks for struct declarations

lib/1.4/dml-builtins.dml
=> Permit custom implementations of register_view

include/simics/dmllib.h
Otherwise, use `SIM_LOG_ERROR`. Needed for compatibility with packages with a Base dependency lower than 6.0.188.
Gonna run PackageTest on this to make sure it works.
=> dmllib.h: Only use `VT_log_warning` if available

RELEASENOTES-1.4.docu, include/simics/dmllib.h, py/dml/codegen.py, py/dml/ctree.py
@TSonono This is intended to solve your problem. Try to check-out this commit in the `src/tools/dmlc` submodule and build DMLC using it, then see if it makes any difference when you try to build your device (I haven't managed to reproduce your issue, which is no surprise given how fickle GCC is about this)
=> Check indices passed to method functions -- SIMICS-22491

RELEASENOTES-1.4.docu, lib/1.2/dml-builtins.dml, lib/1.4/dml-builtins.dml, py/dml/codegen.py, py/dml/compat.py
This is a draft PR in case we decide to go down this route.
=> Add compatibility feature to gate method index assertions

test/tests.py
t126 started failing after merging of #311
=> Added tml file to copyright ignore list

RELEASENOTES-1.4.md, doc/1.4/language.md, py/dml/c_backend.py, py/dml/codegen.py, py/dml/ctree.py, py/dml/dmlparse.py, test/1.4/errors/T_EBTYPE.dml, test/1.4/errors/T_ESYNTAX_time_unit.dml, test/1.4/errors/T_WTTYPEC.dml, test/1.4/events/T_after.dml, test/1.4/events/T_after_cancel.dml, test/1.4/events/T_after_cancel.py
i dislike how obviously-but-not-to-what-degree separate the picosecond clock is
i really want to know about its caveats more
consider this a partially draft PR until we find out more
=> Add picoseconds (`ps`) as a unit of time -- SIMICS-16019

RELEASENOTES-1.4.md, lib/1.2/dml-builtins.dml, lib/1.4/dml-builtins.dml, py/dml/c_backend.py, test/1.4/lib/T_destroy.dml, test/1.4/lib/T_destroy.py, test/1.4/misc/linemarks.dml
This is to get the ball rolling and force you to accept or reject it ;)
=> `destroy` template -- SIMICS-16161

py/dml/toplevel.py, test/tests.py
- **Only load pre-parsed files that end with .dmlast**
=> Only load pre-parsed files that end with .dmlast

RELEASENOTES.md, doc/1.4/language.md, doc/1.4/running-dmlc.md, py/dml/messages.py, py/dml/output.py, py/dml/toplevel.py, test/1.4/errors/T_EPRAGMA.dml, test/1.4/errors/T_ESYNTAX.dml, test/1.4/errors/T_WPRAGMA.dml, test/1.4/pragmas/COVERITY.dml, test/tests.py
Long past time we do this. I'll need a test for the `COVERITY` pragma; I'll probably do something similar to how `linemarks` or `dead_dml_methods` work.
=> Make pragmas official

RELEASENOTES-1.4.md, lib/1.4/dml-builtins.dml, test/1.4/lib/T_partial_access_log.dml, test/1.4/lib/T_partial_access_log.py
Fixes https://github.com/intel/device-modeling-language/issues/356
=> Improve logs for partial read/write access

test/tests.py
It turns out the previous commit didn't work even though I thought I tested it (tested manually on the build machine this time).
=> Fix devnull path in 10d817ea

py/dml/structure.py, py/port_dml.py, test/1.2/misc/porting.dml, test/1.4/misc/porting.dml
=> Polish attribute porting when allocate_type doesn't match type
