intel/device-modeling-language

- RELEASENOTES.docu
- include/simics/dmllib.h
- py/dml/serialize.py
- test/1.4/serialize/T_saved_declaration.dml
- test/1.4/serialize/T_saved_declaration.py
Due to how serializable types work, we can't entirely avoid creating dedicated de/serialization functions for each array type which is implicitly serialized in the program -- however, these functions now simply serve as thin wrappers over calls to _deserialize_array and _serialize_array, which this PR introduces into dmllib.h.
We've discussed revamping the architecture of serialize.py to permit returning set_error_t in the future -- perhaps we could make use of that opportunity to also revamp de/serialization function generation to avoid the generation of these thin wrappers.
> Improve generation of array de/serialization functions -- SIMICS-18440

- RELEASENOTES-1.4.docu
- lib/1.4/utility.dml
- test/1.4/lib/T_map_target_connect.dml
- test/1.4/lib/T_map_target_connect.py
Add map_target template
This template makes the connect represent a Simics `map_target`, which
accepts read and writes to a given address.  This is achieved by the
use of a `map_target_t *` and `SIM_issue_transaction`.
> map_target template

- lib/1.4/utility.dml
- test/1.4/lib/T_map_target_connect.py
Log on level 2 if access fails, level 4 otherwise
> Add logging on map-target access

- README.md
- test/tests.py
If build-deps does not exist, use the default path of GCC. 
Otherwise, a lot of unit tests would end up with the following error message:
FileNotFoundError: [Errno 2] No such file or directory: '/nfs/simics/build-deps/linux64/6.18/packages/gcc_6.4.0/bin/gcc': '/nfs/simics/build-deps/linux64/6.18/packages/gcc_6.4.0/bin/gcc'
> If the preferred GCC path does not exist on Linux, fall back

- include/simics/dmllib.h
- py/dml/c_backend.py
- py/dml/codegen.py
- py/dml/ctree.py
- py/dml/traits_test.py
SSM has encountered issues multiple times relating to .bss being too large due to large arrays of trait vtable instances. Properly addressing this issue requires optimizing the generation and use of vtables such that vtable arrays will no longer be necessary, but the difficulty of implementing that solution justifies implementing a simpler fix in the meantime -- simply allocate trait vtable instances on the heap.
I'm unsure if t126 exhaustively covers every case this change would affect, so this should probably be tested against VP.
> Allocate trait vtable instances on the heap -- quick-fix for SIMICS-18498, SIMICS-18640, SIMICS-18596

- RELEASENOTES.docu
- py/dml/clone_test.py
- py/dml/codegen.py
- py/dml/ctree.py
- py/dml/messages.py
- py/dml/structure.py
- py/dml/types.py
- test/1.2/errors/T_ECONST.dml
- test/1.2/errors/T_EVLACONST.dml
- test/1.2/misc/T_init_data.dml
- test/1.2/statements/T_local_const_struct.dml
- test/1.4/errors/T_ESAVEDCONST.dml
- test/XFAIL
This PR makes DML perform more thorough checks to confirm that assignments aren't done to const-qualified targets. It also rejects (partially) const-qualified VLAs or saved variables. Code generation for various initializers have been rewritten to avoid GCC errors when the destination is (partially) const-qualified, in order to allow for initialization of const-qualified session variables to codegen correctly.
> Improvements on const -- SIMICS-9440, SIMICS-10197

- README.md
- py/README.md
- py/dml/dmlc.py
- test/tests.py
hotshot is not available in Python 3. So setting DMLC_PROFILE would make dmlc fail with following error message:
_ModuleNotFoundError: No module named 'hotshot'_
This pull request fixes the issue by replacing hotshot with cProfile. A unit test was added to cover DMLC_PROFILE.
> Fix dmlc profile

- RELEASENOTES-1.4.docu
- doc/1.4/language.md
- py/dml/dmlparse.py
- py/dml/messages.py
- py/dml/structure.py
- test/1.4/errors/T_EAINCOMP.dml
- test/1.4/errors/T_EAUNKDIMSIZE.dml
HSD-ES ticket 22014423596.
We decided to finish the discussion on this, and settled on `register foo[i < ...]` as the syntax.
> Support omitting object array dimension sizes when redundant -- SIMICS-18580

- doc/1.4/language.md
This solves SIMICS-18692 by making it clear that the section only concern statements that may appear within methods -- including the `local` statement.
> Docs: Rename "Statements" section to "Method Statements" -- SIMICS-18692

- RELEASENOTES-1.4.docu
- doc/1.4/language.md
- py/dml/dmlparse.py
- py/dml/messages.py
- py/dml/structure.py
- test/1.4/errors/T_EAINCOMP.dml
- test/1.4/errors/T_EAUNKDIMSIZE.dml
This reverts commit fa5e26926729d035f54675b4beeb1d2a8f8a1591.
The discussion has been settled: the conclusion is that the workaround for Konstantin's use-case is acceptable. This is due to the rarity of the use-case, together with fact that other solutions to do not significantly improve that use-case, and that those other improvements would be very vulnerable to changes in the model.
> Restore the [i < ...] array syntax.

- README.md
- py/dml/dmlc.py
- py/dml/toplevel.py
- test/tests.py
- Repair and run test
- Provide a sensible default for api_version
- Simplify profiling test case
- Add environment variable DMLC_DUMP_INPUT_FILES
> Add environment variable DMLC_DUMP_INPUT_FILES

- README.md
Update readme to point at the correct location for the public release of the Intel Simics simulator.  Added a bit more substance to the introduction.
> Correct path to public Simics simulator + more

- Makefile
- md_to_github.py
Also don't build wiki as part of 'make dmlc'.
Right now, Simics releases are DMLC releases, so we let the Simics release
infrastructure take care of version annotation.
> Don't forgive missing Simics version

- RELEASENOTES-1.4.docu
- lib/1.4/utility.dml
This allows implementers to override it, and add custom atoms to all transactions
> Make map_target.issue 'default'

- RELEASENOTES-1.2.docu
- RELEASENOTES-1.4.docu
- RELEASENOTES.docu
- Spell DML in uppercase
- Make release note headers abide to Intel standards
> Make release note headers abide to Intel standards

- RELEASENOTES-1.4.docu
- lib/1.4/dml-builtins.dml
- py/dml/c_backend.py
- test/1.4/lib/T_connect.dml
- test/1.4/lib/T_connect.py
> Fix bug in naming when init_as_subobj is instantiated in a bank or port

- test/tests.py
This fixes problems on Ubuntu 20.4, where gcc passes -pie to the linker
by default, which is incompatible with -r. Passing -r to gcc suppresses
this default, whereas -Wl,-r does not.
> Pass -r flag to gcc directly

- test/1.2/misc/register_view_fields.py
Does not add value, and an upcoming bugfix in Simics Base solves the problem.
> Don't expect <undefined> fields in register_view

- lib/1.4/utility.dml
- Clarify the intended use of the read_constant template
- Turn all template references into links
- Remove redundant "Log output: None" statements
> Clean up utility.dml docs

- include/simics/dmllib.h
- py/dml/c_backend.py
- py/dml/clone_test.py
- py/dml/codegen.py
- py/dml/crep.py
- py/dml/ctree.py
- py/dml/messages.py
- py/dml/structure.py
- py/dml/traits.py
- py/dml/traits_test.py
- py/dml/types.py
- test/1.4/errors/T_EASZLARGE.dml
- test/1.4/errors/T_EIDXVAR.dml
- test/1.4/structure/T_trait.dml
- test/1.4/structure/T_trait_largearray.dml
- test/1.4/structure/T_trait_largearray.py
- test/tests.py
- Use indices from traitref, instead of inferring from pointer arithmetic
- Cover nontrivial indexing of session variables
- Rearrange device struct: propagate array dimensions to leaf members
- Rename crep
> vtable array optimizations (branch "pr/rename-crep")

- py/dml/ctree-test.h
- py/dml/ctree_test.py
It detected any 32-bit integer value as being int64
> Repair IS_INT64 macro

- RELEASENOTES-1.4.docu
- lib/1.4/dml-builtins.dml
- test/1.4/lib/T_io_memory.py
- test/1.4/lib/T_transaction.py
- test/common/instrumentation_access_set_value.py
Apart from the effects mentioned in the release note, this also means
that the message can not be suppressed by bank_instrumentation.after_write
> Log messages for unmapped accesses from unmapped_{read,write}

- py/dml/dmlc.py
- py/dml/dmlparse.py
- py/dml/logging.py
- py/dml/messages.py
- py/dml/output.py
- py/dml/toplevel.py
This avoids a weird :1 in some generated #line directives.
> Keep line numbers separately in SimpleSite

- py/dml/ctree.py
The fix addresses also the following warning emitted by Pylint Python linter:
ctree.py:1082:40: E1120: No value for argument 'rh' in staticmethod call (no-value-for-parameter)
> Specify that methods are static

- doc/1.4/language.md
We missed this during the doc week. How _embarrassing_.
> Don't reference register numbers in documentation

- py/port_dml.py
This avoids unconditionally feeding the source file to the lexer,
which hindered a weird non-DML use case of mine.
> Reverse order of conditions

- RELEASENOTES-1.4.docu
- doc/1.4/language.md
- lib/1.2/dml12-compatibility.dml
- lib/1.4/dml-builtins.dml
- test/1.4/lib/T_attributes.dml
It's silly, but we're gonna have to test this against VP. The risk that there's some strange hierarchical conflict when it comes to the `init` definition or a user-rolled definition of `init_val` conflicting is just too high to ignore.
> Add `init_val` param to standard attribute templates -- SIMICS-20108

- py/dml/dmlc.py
- test/tests.py
If a device has no relative imports with `..`, then we created
self-referencing symlinks because we couldn't distinguish between
directories `''` and `'.'`. `normpath` solves the problem.
> Fix bug in DMLC_DUMP_INPUT_FILES

- RELEASENOTES-1.4.docu
- py/dml/serialize.py
- test/1.4/serialize/T_large_struct.dml
- test/1.4/structure/T_diamond_override.dml
- test/XFAIL
- test/tests.py
- remove obsolete XFAIL
- Add test that ambiguous inheritance can be resolved by override
- Avoid having to pass -L when re-running test manually
- Don't declare a temporary struct instance as a local variable
> Don't declare a temporary struct instance as a local variable

- Makefile
- RELEASENOTES.docu
- py/dml/c_backend.py
- py/dml/codegen.py
- py/dml/dmlc.py
- py/dml/globals.py
- py/dml/objects.py
- py/dml/serialize.py
- py/dml/set.py
- py/dml/set_test.py
- py/dml/structure.py
- py/dml/template.py
- py/dml/traits.py
- test/1.2/misc/porting.dml
- test/1.2/registers/T_par_over_endian.dml
- test/1.4/misc/porting.dml
- test/1.4/statements/T_endian_int_aliasing.dml
- test/tests.py
- Adapt to rename of state-change notifier
- Enable line directives by default
- Allow disabling gcc optimizations
- Use dicts and lists instead of sets to avoid indeterministic output
- Sort sets before using, to avoid indeterministic output
- Validate that two runs with different pythons give the same C output
- fix minor typos
- Use ordinary dictionaries
> Make DMLC output deterministic

- RELEASENOTES-1.4.docu
- lib/1.2/dml12-compatibility.dml
- lib/1.4/dml-builtins.dml
- test/1.2/misc/dml14.dml
- test/1.4/lib/T_attributes.dml
This reverts commit f6d442b6126ff46ea9ec5f1ff4d376018509bab6. Reverted due to breaking VP badly enough that resolution warrants thought and discussion.
> Revert "Typed set/get variants for standard attribute templates -- SIMICS-17951"

- RELEASENOTES-1.2.docu
- py/dml/dmlparse.py
- py/dml/messages.py
- py/port_dml.py
- spelling-passlist
- test/1.2/misc/porting.dml
- test/1.4/misc/porting.dml
- test/tests.py
Some users reported that after `int1 x = 1`, the expression `x == 1`
evaluates to `true` in 1.2 and `false` in 1.4; grepping around, this
pattern is fairly common; thus, the uint1 type seems to match better
what int1 means in practice in 1.2.
> Add porting rule for converting int1 to uint1

- include/simics/dmllib.h
- py/dml/c_backend.py
- py/dml/codegen.py
- py/dml/ctree.py
- py/dml/dmlc.py
- py/dml/globals.py
- py/dml/objects.py
- py/dml/serialize.py
- py/dml/structure.py
- py/dml/traits.py
- py/dml/traits_test.py
- py/dml/types.py
- test/1.4/misc/T_dmllib.h
This PR breaks out a couple of miscellaneous (non after-on-hook related) changes in #144 that were done in order to support the after-on-hook changes, in order to help them get approved faster, as they are also relevant for the work on RAII types.
Some of the changes have been tweaked compared to how they appear in #144. In particular, `deserialize_list_to_targets` no longer has the `pre` and `post` parameters, and its `error_out` parameter has become `error_out_at_index`, which also accepts the index of the target at which it is called. This will be relevant for the work on RAII types.
> Miscellaneous changes from #144

- py/dml/toplevel.py
DML 1.2 is marked as legacy in 7, not deprecated.
This is blocking builds in 7 when the major version is bumped.
> Support Simics API 7 for DML 1.2

- test/1.2/events/T_after_chk_dup.py
- test/1.2/events/T_dup.py
- test/1.4/events/T_after_chk.py
- test/tests.py
The new ones were introduced in 6 and old ones are removed or
deprecated in 7.
> Avoid old style command line options (SIMICS-20622)

- lib/1.4/utility.dml
- test/1.4/lib/T_io_memory.dml
- test/1.4/lib/T_io_memory.py
The old PCI framework (pci-bus) depends on function_mapped_bank when
mapping pci_config, and it is natural for devices to transition to
transaction interface as an intermediate step before moving to the new
PCIe framework. Furthermore, the default of use_io_memory changes to
false in Simics 7.
> Support function_mapped_bank on banks with use_io_memory=false

- RELEASENOTES-1.2.docu
- lib/1.2/dml12-compatibility.dml
- lib/1.4/dml12-compatibility.dml
- py/dml/structure.py
- test/1.2/misc/T_import_dml14.dml
- test/1.2/misc/T_utility_14_api.py
- test/1.2/misc/dml14.dml
- test/1.2/registers/T_largearray.py
- test/1.4/lib/T_io_memory.dml
- test/1.4/lib/T_io_memory.py
- test/1.4/lib/T_miss_pattern.py
- test/1.4/lib/T_utility.py
- test/1.4/misc/T_import_dml14.dml
- test/1.4/misc/porting-common-compat.dml
- test/1.4/misc/porting-common.dml
- test/1.4/registers/T_inquiry.py
- test/common/test_register_view.py
- Avoid legacy Register_LE form
- Enable `use_io_memory` for generated io_memory_access overrides
- Make explicit assumptions on use_io_memory
- Use io_memory explicitly in shared 1.2/1.4 banks
> Don't rely on use_io_memory default

- RELEASENOTES-1.4.docu
- py/dml/ctree.py
- test/1.4/expressions/T_each_in.dml
If a top-level object's name equals dev.name, then they could yield
conflicting declarations of the `_each_X__in__NAME` variable.
> Avoid broken C code generation, SIMICS-21044

- test/1.2/structure/T_attribute_throw.py
This is not relevant for the correctness of DMLC. Needed for smoother
migration of:
https://github.com/intel-innersource/applications.simulators.simics.simics-base/pull/3767
> Avoid relying on which exact exception an attribute getter throws

- py/dml/ctree.py
- py/dml/messages.py
- test/1.4/errors/T_WPCAST.dml
Currently limited to only catch when pointers to layouts/endian integers are cast to pointers where the basetype is a non-endian integer.
> Warn about bad pointer-to-pointer casts -- SIMICS-20863

- RELEASENOTES-1.4.docu
- py/dml/ctree.py
- py/dml/serialize.py
- py/dml/types.py
- test/1.4/errors/T_ECAST.dml
- test/1.4/events/T_after.dml
- test/1.4/events/T_after.py
- test/1.4/expressions/T_cast.dml
Our unconstifying logic has always been suspect, but it turns out some pieces are not even tested -- deserialization in particular.
Four different issues, fixes for which have been packaged in three different commits. Check each commit for a brief comment on each.
The burden of maintaining deconstifying logic is a rather compelling argument to try to avoid its need in the first place -- by restricting the places where `const` may occur. We already have some restrictions in place, but only a few are codified in the language, while other are explicit limitations of the compiler, upheld by ICEs, and to be fixed at a later date. If we want to commit to "we don't want to bother with this idiocy" then we need to formalize it. For example, we could say "input parameters may not be (partially) …
> Fix various issues relating to `after` on methods with const parameters

- test/tests.py
Module signing is not needed since Simics-Base 6.0.72.
> Remove module signing

- test/tests.py
Unclear if this makes a difference in practice, but makes logic clearer
> Test distributed API files only

- RELEASENOTES.docu
- doc/1.4/language.md
- py/dml/c_backend.py
- py/dml/messages.py
- py/dml/structure.py
- test/1.2/trivial/T_loggroup_1.dml
- test/1.4/errors/T_ELOGGROUPS.dml
- test/1.4/statements/T_log.dml
- test/1.4/statements/T_log.py
(Edited: see https://github.com/intel/device-modeling-language/pull/186#issuecomment-1602099028)
> Don't rely on UB enum semantics for more than 32 log groups

- RELEASENOTES-1.4.docu
- doc/1.4/language.md
- include/simics/dmllib.h
- lib/1.4/dml-builtins.dml
- py/dml/ast.py
- py/dml/c_backend.py
- py/dml/codegen.py
- py/dml/ctree.py
- py/dml/dmlparse.py
- py/dml/expr.py
- py/dml/globals.py
- py/dml/messages.py
- test/1.4/errors/T_WHOOKSEND.dml
- test/1.4/errors/T_WIMMAFTER.dml
- test/1.4/hooks/T_asynchronous_send.dml
- test/1.4/hooks/T_asynchronous_send.py
- test/1.4/statements/T_immediate_after_basic.dml
- test/1.4/statements/T_immediate_after_basic.py
- test/1.4/statements/T_immediate_after_cancel.dml
- test/1.4/statements/T_immediate_after_cancel.py
- test/1.4/statements/T_immediate_after_entrances.dml
- test/1.4/statements/T_immediate_after_entrances.py
Depends on #144 . Reviewing that should take priority.
This was very quick and easy to do thanks to the architecture revamp that after-on-hooks does... but it just further highlights the copy-pasting necessary from what the architecture does not cover. 1400 insertions, ugh (though admittedly reducing the copy-pasting will just remove like ~350 loc if one is being _extremely_ optimistic, so perhaps it's not as bad as I think).
> Immediate After Statement -- SIMICS-20379

- lib/1.4/utility.dml
In the documentation, these were described in the midst of "Templates for reset"
> Update docs for signal_port and signal_connect

- py/dml/c_backend.py
This is to silence GCC when it decides to make warnings based on bad assumptions about the values that an argument may take.
Or at least, that is what I think is going on. Original issue was reported by @gwikland. I have not been able to create a minimal reproducer, which is why this lacks a test.
The seemingly stochastic nature of the issue _does_ terrify me -- making me doubt myself and wondering if the warning is actually based on a concrete usage rather than GCC assuming something to be possible. However, based on an inspection of the generated code, experimentation, and my previous experience of a similarly stupid error (see #204) I've thoroughly convinced myself that no, GCC really _is_ just deciding to be dumb.
> Trait trampolines: declare `_flat_index` as uint32

- RELEASENOTES.docu
- py/dml/codegen.py
- py/dml/ctree.py
- py/dml/dmlc.py
- py/dml/messages.py
- py/dml/structure.py
- test/1.4/errors/WLOGMIXUP.dml
- test/tests.py
Depends on #186 
The verification of this is gonna be interesting. It will complain about what https://github.com/intel-innersource/applications.simulators.simics.simics-base/pull/4184 addresses, but what else?
> Warn if log groups are used as log level, or vice versa -- SIMICS-21138

- lib/1.4/dml-builtins.dml
- py/dml/c_backend.py
- py/dml/dmlc.py
- py/dml/messages.py
- py/dml/structure.py
- test/tests.py
- Shut up linter
- Remove the --illegal-attrs flag
- Remove --illegal-attrs flag
- Remove --version, which was ignored
- Migrate from optparse to argparse
> Migrate from optparse to argparse

- py/dml/ctree_test.py
Without this change, PR https://github.com/intel-innersource/applications.simulators.simics.simics-base/pull/4984 ends up with:
```
[Step 8/14] FileNotFoundError: [Errno 2] No such file or directory: ' /disk2/conan_build_deps/6.53/gcc-13.1.0/bin/gcc'
```
Notice the extra space. If CCACHE is set to ccache it's equally bad as ctree_test.py does not split CC into multiple arguments passed to subprocess. The assumption is that CC is an undecorated compiler, and this PR does that by using special CC_NO_CCACHE variable.
> Need to run ctree_test.py without decorated ccache

- RELEASENOTES-1.2.docu
- RELEASENOTES-1.4.docu
- RELEASENOTES.docu
In particular, use prefix for the tracker-system, always a space before the
bug-tag, as well as no dot before the tag but after - SIMICS-21408.
> Make releasenotes display consistently

- py/dml/codegen.py
- py/dml/ctree.py
- py/dml/ctree_test.py
- test/1.4/misc/linemarks.dml
This matters for Coverity's `STRAY_SEMICOLON` checker. We didn't notice this before as `If.toc()` always used to emit braces.
@JonatanWaern You have to be the reviewer now as Erik's on vacation.
> Don't transform empty compounds to `;`

- RELEASENOTES.docu
- py/dml/ctree.py
- test/1.4/expressions/T_inlined_param.dml
This sometimes triggered errors in the old PCI library
(`update_mapping("I/O")`)
> Avoid wrapping constants in multiple layers of InlineParam

- py/dml/ctree.py
With #221 these got pretty gnarly: `else if` was turned into:
```
else
{
if (...)
{
...
}
}
```
This restricts brace-wrapping for `If.toc_stmt` to only occur where it matters, eliminating this issue.
> Prettify C generation for `if`-`else` chains

- lib/1.4/dml-builtins.dml
- py/dml/c_backend.py
- py/dml/globals.py
- py/dml/objects.py
- py/dml/serialize.py
- py/dml/structure.py
- py/dml/traits_test.py
- test/1.4/legacy/T_port_proxy_attrs_disabled.dml
- test/1.4/legacy/T_port_proxy_ifaces_disabled.dml
- Fix spelling
- Remove redundant flag
- Make global device list available only during code generation
- Make global hook list available only during code generation
- Only worry about None names in obsolete DML
> Make global device/hook lists available only during code generation

- test/1.2/statements/T_if_ambiguity.dml
To test both our parser's behavior and that generated C doesn't provoke `Wparantheses`.
> Add test for `if`-`else` ambiguity

- py/dml/output.py
This improves defect reporting. Admittedly a rather lazy solution.
> Fix incorrect linemark tracking with `--coverity`

- RELEASENOTES-1.4.docu
- lib/1.4/dml-builtins.dml
- remove unused method
- Use counting sort to sort in linear instead of quadratic time
> Use counting sort to sort in linear instead of quadratic time

- test/1.4/lib/T_signal_templates.py
The reverse exectuion feature is getting removed in 7.
> Don't test reverse execution in Simics 7

- test/tests.py
More recent MinGW versions resolve symlinks when embedded source references in dependecy files.
Hence, the test should also ensure it always uses the resolved locations for both source and target (older MinGW might still not resolve locations, so only resolving one of the two would then confuse these).
> Make test work with sym-linked sources

- RELEASENOTES.docu
- py/dml/structure.py
- test/1.4/types/T_typeof.dml
This fixes an issue when leveraging `typeof`: that a method signature using it would lead to incorrect compile-time errors if the method is overridden.
Ran into this while doing simple regs work. This PR alone should be an uncontroversial fix, however, I am looking warily at other uses of `eval_type` where `None` is passed as the location. Most of it is trait-related, which should really only be able to leverage top-level stuff -- however, today, they can't even do that, as they have no access to even `dev`. That question however should be left to a different PR.
> Leverage location when typechecking method overrides

- RELEASENOTES-1.4.docu
- py/dml/c_backend.py
- test/1.4/misc/T_notify_state.dml
- test/1.4/misc/T_notify_state.py
I kinda sorta forgot about this when I wrote immediate after.
After-on-hooks doesn't have the same problem as messages can only be sent through a hook from within DML itself.
> Fix immediate after callbacks not notifying about state change

- lib/1.4/dml-builtins.dml
... So they are always reachable. Internal as they are stand-ins for the lack of template-qualified method implementation calls.
> Break out default implementations of `read_register`/`write_register`

- RELEASENOTES-1.4.docu
- lib/1.4/utility.dml
- test/1.4/lib/T_miss_pattern.dml
- test/1.4/lib/T_miss_pattern.py
Allow method overrides so models could for instance print out info messages when an unmapped access occurs.
> 1.4:utility.dml: template miss_pattern_bank: Allow method overrides

- lib/1.2/dml-builtins.dml
- lib/1.4/dml-builtins.dml
- py/dml/compat.py
- py/dml/messages.py
- py/dml/toplevel.py
- test/1.2/errors/T_WNOVER.dml
- test/1.4/legacy/T_optional_version_statement_1.3_disabled.dml
- test/1.4/legacy/T_optional_version_statement_1.3_enabled.dml
- test/1.4/legacy/T_optional_version_statement_disabled.dml
- test/1.4/legacy/T_optional_version_statement_enabled.dml
- test/tests.py
- **Use compat features to deprecate bad version statements**
- **Improve wording**
- **Use package_path from Simics base**
> Use compat features to deprecate bad version statements

- doc/1.4/language.md
- lib/1.4/dml-builtins.dml
I thought we already did explicitly say the order of `each`-`in`s was not defined, but nope.
> Document order semantics of `each`-`in` and `init`

- RELEASENOTES-1.4.docu
- doc/1.4/language.md
- lib/1.4/dml-builtins.dml
- py/dml/c_backend.py
- py/dml/codegen.py
- py/dml/ctree.py
- py/dml/messages.py
- py/dml/objects.py
- py/dml/set.py
- py/dml/structure.py
- py/dml/template.py
- py/dml/traits.py
- test/1.2/errors/T_EAMBINH.dml
- test/1.4/errors/T_EAMBINH.dml
- test/1.4/errors/T_EAMBTQMIC.dml
- test/1.4/errors/T_EMEMBER.dml
- test/1.4/errors/T_ENSHAREDTQMIC.dml
- test/1.4/errors/T_ETQMIC.dml
- test/1.4/expressions/T_tqmic.dml
Completely untested save that I checked that one (1) existing 1.4 test still passed and nothing else
Currently limited: you can only make a TQMIC if the template specified actually does provide an implementation of the method. In contrast, you could consider that, in principle, if the specified template doesn't provide an implementation then the TQMIC should resolve to the the nearest ancestor of the specified template that provides an implementation. I couldn't think of a good way to do that however with regular methods (shared methods are easy thanks to the `Trait` architecture.)
> Template-Qualified Method Implementation Calls -- SIMICS-22264

- RELEASENOTES-1.4.docu
- lib/1.4/utility.dml
- test/1.4/lib/T_io_memory.dml
- test/1.4/lib/T_io_memory.py
Legacy pci bus maps pci_config banks as Device/Subdevice + function number instead of bank objects.
When we have 2+ PCI devices in 1 DML device (e.g. by using subdevice) such pcI_config bank can be unreachable because pci bank function number is hardcoded to 255.
This PR introduces a limited scope for function_io_memory - closest port object parent.
> Limited scope for function_io_memory

- py/dml/compat.py
I should've caught this. Sorry.
> Fixup short desc of `broken_conditional_is`

- lib/1.4/dml-builtins.dml
- py/dml/output.py
To fix the novel `null_pointer_dereference_crash/constant` errors. Confirmed locally it works (which is why I accidently created the branch on `intel/device-modeling-language`, as I was forced to be on lrs07 to run Coverity...)
> `dml-builtins.dml`: massage types to soothe Coverity

- py/dml/dmlc.py
This improves GCC's error messages for broken #includes inside header
blocks
> Add linemarks to dmldep.c file

- RELEASENOTES.md
Caught by @jakob-engblom-i. Something must've gone wrong during the .docu to .md migration and automatic conversion
> Fixup badly formatted releasenote

- RELEASENOTES-1.4.md
- py/dml/dmlparse.py
- py/dml/messages.py
- py/dml/provisional.py
- py/dml/structure.py
- test/1.4/provisional/T_explicit_param_decls_EOVERRIDE.dml
- test/1.4/provisional/T_explicit_param_decls_ESYNTAX.dml
I want this in in time for SQPFU.
> Make `explicit_param_decls` stable

- RELEASENOTES-1.4.md
- py/dml/structure.py
- py/dml/traits.py
- py/dml/types.py
- test/1.4/errors/T_EMETH.dml
- test/1.4/errors/T_ETYPE.dml
- test/1.4/methods/T_traitrefs_in_shared_sigs.dml
This allows for the use of any template type in the signature of any shared method. The logic has also been extended to check that each named type in the signature is valid.
This new releasenotes format is confusing me. I can only hope this works.
The validation of shared method signatures, even if unused, could potentially break VP as it happens even if the trait is considered dead. I'll run a pretest just in case.
> Typecheck shared methods after trait processing -- SIMICS-22166

- test/tests.py
Soon in Simics, the access_count is not added for objects that do not need it. So the test class used here does not get the access_count attribute. So the test fails for the expected attributes. By adding it explicitly here, the test will pass.
> Add the access_count explicitly

- test/tests.py
- **Make attributes internal if missing _both_ doc & desc**
- **Make subsequent_log use trait identity as key**
- **Make subsequent log in object arrays work correctly**
- **Make write-outside-fields in registers only log once**
- **Enable "Blocking Issues" github action**
- **Try harder to enable action**
- **Try to enable "Dependent issues" github action**
- **Update test**
- **Add some basic gitignores**
- **Switch to local fork**
- **Remove "Blocking Issues" action**
- **Refactor script to avoid side-effects on toplevel**
- **Generate github wiki**
- **Improve logging test**
- **Mention that sizeoftype does not count as a constant**
- **Move topsort to module traits**
- **Refactor: Move method sorting to traits.py**
- **Improve how irrelevant porting messages are presented.**
- …
> Repair pypy run of WREDUNDANTLEVEL_dep

- syntaxes/Dml.tmlanguage
This is applied to the DML TML file.
The vscode extension needs a new submodule reference after this is merged.
> Add provisional as a keyword in DML

- RELEASENOTES.md
- lib/1.2/dml-builtins.dml
- lib/1.4/dml-builtins.dml
- test/1.2/errors/EERRSTMT_dml14.dml
- test/1.4/errors/T_EERRSTMT.dml
~This exists purely for TC to be aware of it.~ Now a proper PR.
> Relax rule for naming groups 'port'/'bank'

- README.md
- py/dml/dmlc.py
- test/tests.py
Not all Pythons are built with xz compression.
> Avoid dependency on liblzma

- lib/1.4/dml-builtins.dml
- **Make attributes internal if missing _both_ doc & desc**
- **Make subsequent_log use trait identity as key**
- **Make subsequent log in object arrays work correctly**
- **Make write-outside-fields in registers only log once**
- **Enable "Blocking Issues" github action**
- **Try harder to enable action**
- **Try to enable "Dependent issues" github action**
- **Update test**
- **Add some basic gitignores**
- **Switch to local fork**
- **Remove "Blocking Issues" action**
- **Refactor script to avoid side-effects on toplevel**
- **Generate github wiki**
- **Improve logging test**
- **Mention that sizeoftype does not count as a constant**
- **Move topsort to module traits**
- **Refactor: Move method sorting to traits.py**
- **Improve how irrelevant porting messages are presented.**
- …
> Let register_view_catalog depend on _provide_register_view

- doc/1.4/language.md
- **Make attributes internal if missing _both_ doc & desc**
- **Make subsequent_log use trait identity as key**
- **Make subsequent log in object arrays work correctly**
- **Make write-outside-fields in registers only log once**
- **Enable "Blocking Issues" github action**
- **Try harder to enable action**
- **Try to enable "Dependent issues" github action**
- **Update test**
- **Add some basic gitignores**
- **Switch to local fork**
- **Remove "Blocking Issues" action**
- **Refactor script to avoid side-effects on toplevel**
- **Generate github wiki**
- **Improve logging test**
- **Mention that sizeoftype does not count as a constant**
- **Move topsort to module traits**
- **Refactor: Move method sorting to traits.py**
- **Improve how irrelevant porting messages are presented.**
- …
> Remove obsolete note, SIMICS-22784

- test/1.4/hooks/T_checkpointing.cont.py
- test/1.4/hooks/T_checkpointing.py
> Avoid deprecated command line parameters

- RELEASENOTES.md
- doc/1.4/language.md
- lib/1.2/dml-builtins.dml
- lib/1.4/dml-builtins.dml
- py/dml/codegen.py
- py/dml/compat.py
- py/dml/messages.py
- test/1.4/legacy/T_meaningless_log_levels_disabled.dml
- test/1.4/legacy/T_meaningless_log_levels_enabled.dml
- test/1.4/legacy/T_meaningless_log_levels_enabled.py
- test/1.4/legacy/meaningless_log_levels.dml
- test/1.4/statements/T_subsequent_log.dml
- test/1.4/statements/T_subsequent_log.py
This adds support for `1 then 5` for `warning`, `error` and `critical`, as well as restricting the valid log levels for these to 1 (and 5)
SIMICS-22401 is not a **perfect** fit for this, but it mentions log level 0, which was part of the original discussion about how we should treat `warning`, `error` and `critical`.
> Polish treatment of log levels for error-like log kinds -- SIMICS-22401

- lib/1.2/dml-builtins.dml
- lib/1.4/dml-builtins.dml
- **Make attributes internal if missing _both_ doc & desc**
- **Make subsequent_log use trait identity as key**
- **Make subsequent log in object arrays work correctly**
- **Make write-outside-fields in registers only log once**
- **Enable "Blocking Issues" github action**
- **Try harder to enable action**
- **Try to enable "Dependent issues" github action**
- **Update test**
- **Add some basic gitignores**
- **Switch to local fork**
- **Remove "Blocking Issues" action**
- **Refactor script to avoid side-effects on toplevel**
- **Generate github wiki**
- **Improve logging test**
- **Mention that sizeoftype does not count as a constant**
- **Move topsort to module traits**
- **Refactor: Move method sorting to traits.py**
- **Improve how irrelevant porting messages are presented.**
- …
> Provide conf_object_t definition in dml-builtins

- test/tests.py
This is to work around what seems to be a bug with Pypy on Windows, where regex fails to handle carriage returns properly.
> Test annotation parsing: strip line endings

- lib/1.4/dml-builtins.dml
See HSD-ES [14024395007](https://hsdes.intel.com/appstore/article/#/14024395007). To my confusion it seems no JIRA issue has automatically been created for it? Is the bridge slow or is something missing for it to kick in? For the moment, I'm citing the number directly in the commit message, but I'd like to ref the JIRA instead.
@JonatanWaern Erik's on vacation, so you'll have to be the reviewer.
> `destroy` template: clarify program exit semantics -- SIMICS-23025

- doc/1.4/language.md
- lib/1.4/dml-builtins.dml
The documentation was only partially corrected regarding these in 2021 in commit b6f8d3097d7ff779c7261a0d389a7831698964ae in Simics-Base (back when DMLC was part of that repository).
Also fix a documentation typo in dml-builtins.dml.
> doc: Correct read_bits/write_bits -> read_field/write_field

- test/tests.py
The path resolve of os.devnull has changed a bit after Python 3.10.
> Make "empty" test compatible with newer Python

- test/tests.py
This was removed in 41a745c6 but it turns out to be needed.
> Put back Python version condition

- py/port_dml.py
- test/tests.py
Such failures are usually not so bad, so port-dml-module
wants to spot the difference and proceed.
> Use exit code 2 for partial failure

- include/simics/dmllib.h
*Yes*, Coverity is apparently **too stupid** to understand variadic arguments.
> dmllib.h: Suppress Coverity false positives w.r.t. `va_start`

- doc/1.4/changes-manual.md
I haven't checked whether these would be caught by --strict-dml12. I guessed that they would not. Do you know off-hand if this is true?
> Update changes-manual: unmapped fields and constant registers
